# site settings
title: OBA
subtitle: 
email: oba2311@gmail.com
description: I'm Omer, a product manager focused on data-intensive products.<br /> For the past 10 years I've been working mostly with startups on strategy and products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oba2311.github.io/website" # the base hostname & protocol for your site
author:
city: TLV
country: IL

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
instagram_url: https://www.instagram.com/omerbenami16/
linkedin_url: https://www.linkedin.com/in/omer-ben-ami/
twitter_url: https://twitter.com/Omer_Ben_Ami

# build settings
markdown: kramdown

sass:
  style: compressed
